{{- with .Values.postgresqlExternal }}
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ include "jet-chart.fullname" $ }}-postgresql
subsets:
  - addresses:
      - ip: {{ .IP }}
    ports:
      - port: {{ .port }}
{{- end }}
