{{- $airbaseRules := list }}
{{- $airbaseRules = append $airbaseRules (printf "Host(`%s`) && Path(`%s`)" .Values.jetHost (include "jet-chart.build-path" (merge (dict "path" "/api") .))) }}
{{- $airbaseRules = append $airbaseRules (printf "Host(`%s`) && Path(`%s`)" .Values.jetHost (include "jet-chart.build-path" (merge (dict "path" "/explorer") .))) }}

{{- $airbaseRules = append $airbaseRules (printf "Host(`%s`) && PathPrefix(`%s`)" .Values.jetHost (include "jet-chart.build-path" (merge (dict "path" "/subscriptions") .))) }}
{{- $airbaseRules = append $airbaseRules (printf "Host(`%s`) && PathPrefix(`%s`)" .Values.jetHost (include "jet-chart.build-path" (merge (dict "path" "/live") .))) }}

{{- $airbaseRules = append $airbaseRules (printf "Host(`%s`) && PathPrefix(`%s`)" .Values.jetHost (include "jet-chart.build-path" (merge (dict "path" "/oss") .))) }}
{{- $airbaseRules = append $airbaseRules (printf "Host(`%s`) && PathPrefix(`%s`)" .Values.jetHost (include "jet-chart.build-path" (merge (dict "path" "/ops") .))) }}

{{/* Middlewares for web ingress-routes */}}
{{- $webMiddlewares := list }}
{{- $webMiddlewares = append $webMiddlewares "strip-subpath" }}
{{- $webMiddlewares = append $webMiddlewares "compress" }}
{{- if .Values.jetTLSSecret | empty | not }}
{{- $webMiddlewares = append $webMiddlewares "redirect-to-https" }}
{{- end }}

{{/* Middlewares for websecure ingress-routes */}}
{{- $websecureMiddlewares := list }}
{{- $websecureMiddlewares = append $websecureMiddlewares "strip-subpath" }}
{{- $websecureMiddlewares = append $websecureMiddlewares "compress" }}

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "jet-chart.fullname" . }}-jet-web
spec:
  entryPoints:
    - web
  routes:
    {{- range $airbaseRules }}
    - match: {{ . }}
      kind: Rule
      services:
        - name: {{ include "jet-chart.fullname" $ }}-airbase
          port: 80
      middlewares:
        {{- range $webMiddlewares }}
        - name: {{ include "jet-chart.fullname" $ }}-{{ . }}
        {{- end}}
    {{- end }}
---

{{- if .Values.jetTLSSecret | empty | not }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "jet-chart.fullname" . }}-jet-websecure
spec:
  entryPoints:
    - websecure
  routes:
    {{- range $airbaseRules }}
    - match: {{ . }}
      kind: Rule
      services:
        - name: {{ include "jet-chart.fullname" $ }}-airbase
          port: 80
      middlewares:
        {{- range $websecureMiddlewares }}
        - name: {{ include "jet-chart.fullname" $ }}-{{ . }}
        {{- end}}
    {{- end }}
  tls:
    secretName: {{ include "jet-chart.fullname" $ }}-jet-tls-secret
{{- end }}
