{{- $rules := list }}
{{- $rules = append $rules (printf "Host(`%s`) && PathPrefix(`%s`)" .Values.minioHost (include "jet-chart.build-path" (dict "prefix" .Values.minioSubpath "path" .Values.airbaseOSSPrivateBucket))) }}
{{- $rules = append $rules (printf "Host(`%s`) && PathPrefix(`%s`)" .Values.minioHost (include "jet-chart.build-path" (dict "prefix" .Values.minioSubpath "path" .Values.airbaseOSSPublicBucket))) }}

{{/* Middlewares for web ingress-routes */}}
{{- $webMiddlewares := list }}
{{- $webMiddlewares = append $webMiddlewares "compress" }}
{{- if .Values.minioTLS | empty | not }}
{{- $webMiddlewares = append $webMiddlewares "redirect-to-https" }}
{{- end }}

{{/* Middlewares for websecure ingress-routes */}}
{{- $websecureMiddlewares := list }}
{{- $websecureMiddlewares = append $websecureMiddlewares "compress" }}

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "jet-chart.fullname" . }}-minio
spec:
  entryPoints:
    - web
  routes:
    {{- range $rules }}
    - match: {{ . }}
      kind: Rule
      services:
        {{- if .Values.minioExternal }}
        - name: {{ include "jet-chart.fullname" $ }}-minio
          port: 9000
        {{- else }}
        - name: {{ .Values.minioService }}
          port: 9000
        {{- end }}
      middlewares:
        {{- range $webMiddlewares }}
        - name: {{ include "jet-chart.fullname" $ }}-{{ . }}
        {{- end}}
    {{- end }}

---

{{- if .Values.minioTLS | empty | not }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "jet-chart.fullname" . }}-minio-websecure
spec:
  entryPoints:
    - websecure
  routes:
    {{- range $rules }}
    - match: {{ . }}
      kind: Rule
      services:
        {{- if .Values.minioExternal }}
        - name: {{ include "jet-chart.fullname" $ }}-minio
          port: 9000
        {{- else }}
        - name: {{ .Values.minioService }}
          port: 9000
        {{- end }}
      middlewares:
        {{- range $websecureMiddlewares }}
        - name: {{ include "jet-chart.fullname" $ }}-{{ . }}
        {{- end}}
    {{- end }}
  tls:
    {{- if .Values.minioTLS.certResolver }}
    certResolver: {{ .Values.minioTLS.certResolver }}
    {{- else if .Values.minioTLS.minioTLSSecret }}
    secretName: {{ include "jet-chart.fullname" $ }}-jet-tls-secret
    {{- end }}
{{- end }}
