version: '3.2'
services:
  minio:
    image: minio/minio:RELEASE.2022-04-01T03-41-39Z
    volumes:
      - ./volume/data/minio/data:/data
    environment:
      - MINIO_BROWSER=off
    env_file:
      - external-services.env
      - external-services.local.env
    command: server /data
    restart: unless-stopped
    ports:
      - 9000:9000
    networks:
      - external-services-network
