apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: {{ include "jet-chart.fullname" . }}-postgresql-backup
  labels:
    {{- include "jet-chart.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.backup.veleroSchedule }}
  template:
    defaultVolumesToFsBackup: true
    includedNamespaces:
      {{- range .Values.backup.includeNamespaces }}
      - {{ . }}
      {{- end }}
    labelSelector:
      matchLabels:
        {{- .Values.backup.selector | toYaml | nindent 8 }}
    storageLocation: {{ .Values.backup.storageLocation }}
    ttl: {{ .Values.backup.ttl }}

