apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jet-chart.fullname" . }}-minio
  labels:
    {{- include "jet-chart.labels" . | nindent 4 }}
data:
  MINIO_ROOT_USER: {{ .Values.minioRootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minioRootPassword | quote }}
  JET_STORAGE_SCHEME: {{ .Values.minioScheme }}
  JET_STORAGE_HOST: {{ .Values.minioHost }}
  JET_STORAGE_PORT: {{ .Values.minioPort | quote }}
  JET_STORAGE_FASTLINE_SCHEME: "http://"
  {{- if .Values.minioExternal }}
  JET_STORAGE_FASTLINE_HOST: {{ include "jet-chart.fullname" . }}-minio
  {{- else }}
  JET_STORAGE_FASTLINE_HOST: {{ .Values.minioService }}
  {{- end }}
  JET_STORAGE_FASTLINE_PORT: "9000"
