{{- with .Values.minioExternal }}
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ include "jet-chart.fullname" $ }}-minio
subsets:
  - addresses:
      - ip: {{ .IP }}
    ports:
      - port: {{ .port }}
{{- end }}
